name: cryptohub
description: "A Flutter application built with Clean Architecture, featuring secure authentication, cryptocurrency management, and user profile functionalities. The app supports light and dark themes, unit/widget tests for key components, and secure token storage."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  freezed: ^2.3.4
  freezed_annotation: ^2.2.0
  flutter_bloc: ^9.1.0
  dio: ^5.8.0+1
  go_router: ^14.8.1
  get_it: ^8.0.3
  rxdart: ^0.28.0
  dartz: ^0.10.1
  json_annotation: ^4.9.0
  flutter_svg: ^2.0.17
  collection: ^1.19.1
  shimmer: ^3.0.0
  flutter_secure_storage: ^9.2.4
  bloc_test: ^10.0.0
  mocktail: ^1.0.4
  mockito: ^5.4.5

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0
  build_runner:
  json_serializable: ^6.5.0


flutter:


  uses-material-design: true
